name: Multi-Platform Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type ("patch"|"minor"|"major")'
        required: true
        default: "patch"
jobs:
  version-increment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Setup env
        run: |
          git config --global credential.helper store
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: giloushaker/nr-translation
          submodules: true
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Set Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Bump version with npm (uses default commit message)
        id: version_bump
        run: |
          VERSION=$(npm version ${{ github.event.inputs.version }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Push commit and tag
        run: |
          git push origin HEAD
          git push origin refs/tags/${{ steps.version_bump.outputs.version }}

  build-ghpages:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Setup environment
        run: |
          git config --global credential.helper store
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: giloushaker/nr-translation
          submodules: true
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Run version increment script
        id: version_script
        run: node ./increment-version.js

      - name: Install dependencies
        run: npm ci

      - name: Build application for GitHub Pages
        run: npm run generate -- --ghpages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
